# Generated by Django 5.2.1 on 2025-05-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
